import os
import sys
import json
import base64

class CodeGen:
    """
    Generates a standalone Python bootstrap that embeds
    the Untold runtime + user source, runnable anywhere.
    """

    RUNTIME_MODULES = [
        "src/lexer/tokens.py",
        "src/lexer/lexer.py",
        "src/parser/ast_nodes.py",
        "src/parser/parser.py",
        "src/interpreter/environment.py",
        "src/interpreter/interpreter.py",
        "stdlib/fs.py",
        "stdlib/shell.py",
        "stdlib/web.py",
        "stdlib/net.py",
        "stdlib/ai.py",
        "stdlib/hack.py",
    ]

    def __init__(self, project_root):
        self.project_root = project_root

    def generate(self, bundled_source, output_path):
        """Generate a self-contained Python script."""

        # Embed all runtime modules as base64
        modules = {}
        for rel_path in self.RUNTIME_MODULES:
            abs_path = os.path.join(self.project_root, rel_path)
            if os.path.exists(abs_path):
                with open(abs_path, "r", encoding="utf-8") as f:
                    modules[rel_path] = f.read()

        # Build the bootstrap script
        bootstrap = self._build_bootstrap(bundled_source, modules)

        with open(output_path, "w", encoding="utf-8") as f:
            f.write(bootstrap)

        return output_path

    def _build_bootstrap(self, source, modules):
        # Encode modules as JSON embedded in the script
        modules_json = json.dumps(modules)
        source_b64   = base64.b64encode(source.encode()).decode()

        return f'''#!/usr/bin/env python3
# Generated by Untold Lang compiler v0.1.0
# This file is self-contained — no external dependencies needed

import sys
import os
import json
import base64
import importlib.util
import types

# ── Embedded runtime ──────────────────────────────────────────
_MODULES = json.loads({repr(modules_json)})
_SOURCE  = base64.b64decode({repr(source_b64)}).decode()

def _load_embedded(module_name, code):
    spec   = importlib.util.spec_from_loader(module_name, loader=None)
    module = types.ModuleType(module_name)
    exec(compile(code, module_name, "exec"), module.__dict__)
    sys.modules[module_name] = module
    return module

# Load runtime modules in order
_path_to_modname = {{
    "src/lexer/tokens.py":               "src.lexer.tokens",
    "src/lexer/lexer.py":                "src.lexer.lexer",
    "src/parser/ast_nodes.py":           "src.parser.ast_nodes",
    "src/parser/parser.py":              "src.parser.parser",
    "src/interpreter/environment.py":    "src.interpreter.environment",
    "src/interpreter/interpreter.py":    "src.interpreter.interpreter",
    "stdlib/fs.py":                      "stdlib.fs",
    "stdlib/shell.py":                   "stdlib.shell",
    "stdlib/web.py":                     "stdlib.web",
    "stdlib/net.py":                     "stdlib.net",
    "stdlib/ai.py":                      "stdlib.ai",
    "stdlib/hack.py":                    "stdlib.hack",
}}

# Create package stubs
for pkg in ["src", "src.lexer", "src.parser", "src.interpreter", "stdlib"]:
    if pkg not in sys.modules:
        sys.modules[pkg] = types.ModuleType(pkg)

for rel_path, mod_name in _path_to_modname.items():
    if rel_path in _MODULES:
        _load_embedded(mod_name, _MODULES[rel_path])

# ── Run the program ───────────────────────────────────────────
from src.lexer.lexer             import Lexer
from src.parser.parser           import Parser
from src.interpreter.interpreter import Interpreter

try:
    tokens = Lexer(_SOURCE).tokenize()
    ast    = Parser(tokens).parse()
    Interpreter().run(ast)
except SyntaxError as e:
    print(f"[Untold SyntaxError] {{e}}", file=sys.stderr)
    sys.exit(1)
except Exception as e:
    print(f"[Untold Error] {{e}}", file=sys.stderr)
    sys.exit(1)
'''